"""Derived, non-authoritative execution telemetry vocabulary."""

TELEMETRY_CLASSIFICATION = "DERIVED_OBSERVATION_ONLY"

EVENT_CLASSES = frozenset({
    "INSTRUCTION_ISSUED",
    "SLOT_ASSIGNED",
    "SLOT_REASSIGNED",
    "EXECUTION_STARTED",
    "EXECUTION_COMPLETED",
    "EXECUTION_BLOCKED",
    "REVIEW_REQUESTED",
    "REVIEW_RESULT",
    "FINDING_CREATED",
    "REMEDIATION_AUTHORIZED",
    "RE_REVIEW_RESULT",
    "REMOTE_EVIDENCE_OBSERVED",
    "PUBLICATION_BOUNDARY_TRANSITION",
})
